GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
GET http://localhost:3003/api/blogs/636f67a03c5e1ce2e0e43cc3/comments

###
POST http://localhost:3003/api/blogs/636f67a03c5e1ce2e0e43cc3/comments HTTP/1.1
content-type: application/json

{
  "comment": "niin on"
}


###
POST http://localhost:3003/api/blogs/63695b7d3dd07e1f4b8590d8 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmVuIiwiaWQiOiI2MzY2MmVkNmUyMDdhY2M3NTI4MDYxMDEiLCJpYXQiOjE2Njc4NDk3MjV9.oCqlZoIpybS3I0khYzW43A_p9vQMBbCMLkPH9pS5roc


{
  "title": "Testiblogi",
  "author": "Leevi",
  "url": "www.leevi.com",
  "likes": 30
}


###
DELETE http://localhost:3003/api/blogs/635ff8576c597973c0040eac

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
  "username": "testinen",
  "name": "testinen testi",
  "password": "123321"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "username": "testinen",
  "name": "testinen testi",
  "password": "123321"
}


###
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
  "username": "testinen",
  "password": "123321"
}

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
  "username": "teds",
  "name": "te",
  "password": "123321"
}